openapi: 3.0.0
info:
  title: Image Processing API
  description: API for performing various image processing operations such as flipping, rotating, greyscaling, resizing, and generating thumbnails.
  version: "2.0.0"
servers:
  - url: http://localhost:3000
paths:
  /upload:
    post:
      summary: Uploads an image and returns its Base64 URL.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Successfully uploaded and converted the image to Base64.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded.
  /applyOperations:
    post:
      summary: Apply selected operations to an image.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                imageType:
                  type: string
                operations:
                  type: array
                  items:
                    type: object
                    properties:
                      operation:
                        type: string
                      param:
                        type: object
                        properties:
                          angle:
                            type: integer
                            description: "Required for angleRotating operation. Specifies the rotation angle."
                          percentage:
                            type: integer
                            description: "Required for resizing operation. Specifies the resize percentage."
                        additionalProperties: false
      responses:
        200:
          description: Operations applied successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                  thumbnailImageUrl_Ops:
                    type: string
        400:
          description: Missing data or no operation specified.
        500:
          description: Server error.
  /verticalFlip:
    post:
      summary: Vertically flips the uploaded image.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Image flipped vertically successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded.
  /horizontalFlip:
    post:
      summary: Horizontally flips the uploaded image.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Image flipped horizontally successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded.
  /colorToGrey:
    post:
      summary: Converts the uploaded image to greyscale.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Image converted to greyscale successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded.
  /rightRotating:
    post:
      summary: Rotates the uploaded image 90 degrees to the right.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Image rotated 90 degrees to the right successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded.
  /leftRotating:
    post:
      summary: Rotates the uploaded image 90 degrees to the left.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Image rotated 90 degrees to the left successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded.
  /angleRotating:
    post:
      summary: Rotates the uploaded image by a specified angle.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageRequestWithAngle'
      responses:
        200:
          description: Image rotated by the specified angle successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded or invalid angle specified.
  /resizing:
    post:
      summary: Resizes the uploaded image by a specified percentage.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageRequestWithPercentage'
      responses:
        200:
          description: Image resized by the specified percentage successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded or invalid percentage specified.
  /generatingThumbnail:
    post:
      summary: Generates a thumbnail for the uploaded image.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Thumbnail generated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
        400:
          description: No file uploaded.

components:
  schemas:
    ImageRequestWithAngle:
      type: object
      required:
        - imageData
        - imageType
        - angle
      properties:
        imageData:
          type: string
        imageType:
          type: string
        angle:
          type: integer
          description: The angle in degrees to rotate the image.

    ImageRequestWithPercentage:
      type: object
      required:
        - imageData
        - imageType
        - percentage
      properties:
        imageData:
          type: string
        imageType:
          type: string
        percentage:
          type: integer
          description: The percentage to resize the image, where 100 maintains original size.

         
