openapi: '3.0.2'
info:
  title: IP_API
  version: '1.0'
servers:
  - url: https://localhost:3000
paths:
  /resizeUpload:
    post:
      summary: Upload an image.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully uploaded the image.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageName:
                    type: string
                    example: 
        '500':
          description: Internal Server Error

  /verticalFlip:
    get:
      summary: Flip an image vertically.
      parameters:
        - in: query
          name: imageName
          schema:
            type: string
          required: true
          description: The name of the image to be flipped.
      responses:
        '200':
          description: Successfully flipped the image vertically.
          content:
            application/json:
              schema:
                type: object
                properties:
                  verticalFlip:
                    type: string
                    example: verti_1611234567890.jpg
        '500':
          description: Internal Server Error

  /horizontalFlip:
    get:
      summary: Flip an image horizontally.
      parameters:
        - in: query
          name: imageName
          schema:
            type: string
          required: true
          description: The name of the image to be flipped.
      responses:
        '200':
          description: Successfully flipped the image horizontally.
          content:
            application/json:
              schema:
                type: object
                properties:
                  horizontalFlip:
                    type: string
                    example: hori_1611234567890.jpg
        '500':
          description: Internal Server Error


  /leftRotating:
    get:
      summary: Rotate an image -90 degrees.
      parameters:
        - in: query
          name: imageName
          schema:
            type: string
          required: true
          description: The name of the image to be rotated.
      responses:
        '200':
          description: Successfully rotated the image to the left.
          content:
            application/json:
              schema:
                type: object
                properties:
                  leftRotated:
                    type: string
                    example: left_rotated_1611234567890.jpg
        '500':
          description: Internal Server Error

  /rightRotating:
    get:
      summary: Rotate an image +90 degrees.
      parameters:
        - in: query
          name: imageName
          schema:
            type: string
          required: true
          description: The name of the image to be rotated.
      responses:
        '200':
          description: Successfully rotated the image to the right.
          content:
            application/json:
              schema:
                type: object
                properties:
                  rightRotated:
                    type: string
                    example: right_rotated_1611234567890.jpg
        '500':
          description: Internal Server Error

  /generatingThumbnail:
    get:
      summary: Generate a thumbnail for an image.
      parameters:
        - in: query
          name: imageName
          schema:
            type: string
          required: true
          description: The name of the image to generate a thumbnail for.
      responses:
        '200':
          description: Successfully generated a thumbnail.
          content:
            application/json:
              schema:
                type: object
                properties:
                  thumbnail:
                    type: string
                    example: thumbnail_1611234567890.jpg
        '500':
          description: Internal Server Error
