openapi: '3.0.2'
info:
  title: CS5200_IP_API_V2
  version: '1.0'
servers:
  - url: https://localhost:3000
paths:
  /upload:
    post:
      summary: Upload an image.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully uploaded the image.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No file uploaded.
        '500':
          description: Internal Server Error

  /verticalFlip:
    post:
      summary: Flip an image vertically.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                  description: Base64 encoded image data.
                imageType:
                  type: string
                  description: MIME type of the image.
      responses:
        '200':
          description: Successfully flipped the image vertically.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No image data provided.
        '500':
          description: Internal Server Error

  /horizontalFlip:
    post:
      summary: Flip an image horizontally.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                  description: Base64 encoded image data.
                imageType:
                  type: string
                  description: MIME type of the image.
      responses:
        '200':
          description: Successfully flipped the image horizontally.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No image data provided.
        '500':
          description: Internal Server Error

  /leftRotating:
    post:
      summary: Rotate an image -90 degrees.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                  description: Base64 encoded image data.
                imageType:
                  type: string
                  description: MIME type of the image.
      responses:
        '200':
          description: Successfully rotated the image to the left.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No image data provided.
        '500':
          description: Internal Server Error

  /rightRotating:
    post:
      summary: Rotate an image +90 degrees.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                  description: Base64 encoded image data.
                imageType:
                  type: string
                  description: MIME type of the image.
      responses:
        '200':
          description: Successfully rotated the image to the right.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No image data provided.
        '500':
          description: Internal Server Error

  /generatingThumbnail:
    post:
      summary: Generate a thumbnail for an image.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                  description: Base64 encoded image data.
                imageType:
                  type: string
                  description: MIME type of the image.
      responses:
        '200':
          description: Successfully generated a thumbnail.
          content:
            application/json:
              schema:
                type: object
                properties:
                  thumbnailUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No image data provided.
        '500':
          description: Internal Server Error
  
  /colorToGrey:
    post:
      summary: Convert an image to greyscale.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                  description: Base64 encoded image data.
                imageType:
                  type: string
                  description: MIME type of the image.
      responses:
        '200':
          description: Successfully converted the image to greyscale.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No image data provided.
        '500':
          description: Internal Server Error

  /angleRotating:
    post:
      summary: Rotate an image by a user-specified angle.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                  description: Base64 encoded image data.
                imageType:
                  type: string
                  description: MIME type of the image.
                rotationAngle:
                  type: integer
                  description: The angle in degrees by which to rotate the image.
      responses:
        '200':
          description: Successfully rotated the image by the specified angle.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No image data provided.
        '500':
          description: Internal Server Error

  /resizing:
    post:
      summary: Resize an image by a user-specified percentage.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageData:
                  type: string
                  description: Base64 encoded image data.
                imageType:
                  type: string
                  description: MIME type of the image.
                percentage:
                  type: integer
                  description: The percentage by which to resize the image.
      responses:
        '200':
          description: Successfully resized the image by the specified percentage.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
        '400':
          description: Bad request. No image data provided.
        '500':
          description: Internal Server Error
